/**
 * Draw.io Tools - Optional enhancement utilities for drawio-skill
 *
 * This module provides validation, repair, and operation capabilities
 * for .drawio files generated by the Claude Code Skill.
 */

// Setup DOM environment first
import './dom-setup.js';

// Core validation
import { validateMxCellStructure, autoFixXml, validateAndFixXml } from './xml-validation.js';

// Diagram operations
export type { DiagramOperation, OperationError, ApplyOperationsResult } from './diagram-operations.js';
export { applyDiagramOperations } from './diagram-operations.js';

// History management
export { addHistory, getHistory, getHistoryEntry, updateLastHistorySvg, clearHistory } from './history.js';

// Shared types
export * from './types.js';

// Validation exports
export { validateMxCellStructure, autoFixXml, validateAndFixXml };

/**
 * Validate draw.io XML
 * @param xml - The XML string to validate
 * @returns Validation result with error if invalid
 */
export function validateDrawioXML(xml: string): { valid: boolean; error?: string } {
  const error = validateMxCellStructure(xml);
  return {
    valid: !error,
    error: error || undefined
  };
}

/**
 * Repair draw.io XML
 * @param xml - The XML string to repair
 * @returns Repair result with fixed XML and list of fixes
 */
export function repairDrawioXML(xml: string): { repaired: boolean; repairedXML?: string; fixedIssues?: string[] } {
  const { fixed, fixes } = autoFixXml(xml);

  // Check if anything was fixed
  const repaired = fixes.length > 0;

  return {
    repaired,
    repairedXML: repaired ? fixed : undefined,
    fixedIssues: repaired ? fixes : undefined
  };
}

/**
 * Quick validation helper for files
 * @param filePath - Path to .drawio file
 * @returns Validation result
 * @example
 * import { quickValidate } from 'drawio-skill/tools';
 * const result = await quickValidate('./drawio/my-diagram.drawio');
 * if (!result.valid) {
 *   console.error('Validation errors:', result.error);
 * }
 */
export async function quickValidate(filePath: string) {
  const fs = await import('fs/promises');
  const xml = await fs.readFile(filePath, 'utf-8');
  return validateDrawioXML(xml);
}

/**
 * Quick repair helper for files
 * @param filePath - Path to .drawio file
 * @returns Repair result
 * @example
 * import { quickRepair } from 'drawio-skill/tools';
 * const result = await quickRepair('./drawio/my-diagram.drawio');
 * if (result.repaired) {
 *   console.log('Fixed issues:', result.fixedIssues);
 * }
 */
export async function quickRepair(filePath: string) {
  const fs = await import('fs/promises');
  const xml = await fs.readFile(filePath, 'utf-8');
  const result = repairDrawioXML(xml);

  if (result.repaired && result.repairedXML) {
    await fs.writeFile(filePath, result.repairedXML, 'utf-8');
  }

  return result;
}
